apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: workshop-demo
spec:
  ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
    deploymentconfig: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}